use_frameworks!
platform :ios, '9.0'

target 'ExhibitionSwift_Example' do
  pod 'ExhibitionSwift', :path => '../'

  target 'ExhibitionSwift_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
